server:
  port: 7777

# jdbc:mysql://localhost:3306/testdb?useUnicode=true&characterEncoding=utf8&allowPublicKeyRetrieval=true&useSSL=false
# jdbc:mysql://localhost:3306/testdb?serverTimezone=UTC&useSSL=false

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/testdb?serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: qAqR1532!#
    driver-class-name: com.mysql.cj.jdbc.Driver

# org.hibernate.dialect.MySQL5InnoDBDialect
  jpa:
    open-in-view: false
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update

  jackson:
    serialization:
      fail-on-empty-beans: false

# jpa 디버깅하려면 집어넣어야 함
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
    app:
      sample:
        message:
          AuditingFilter: DEBUG
          SecurityChecker: DEBUG
          MessageService: DEBUG